# Generated by Django 5.1.5 on 2025-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moteurrecherche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.CharField(choices=[('pdf', 'Pdf'), ('doc', 'Doc'), ('docx', 'Docx'), ('png', 'Png'), ('jpg', 'Jpg'), ('jpeg', 'Jpeg'), ('csv', 'Csv'), ('xslx', 'Xlsx'), ('txt', 'Txt')], default='', max_length=10),
        ),
    ]
