# Generated by Django 5.1.5 on 2025-03-23 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moteurrecherche', '0002_alter_document_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('requestAt', models.DateTimeField(auto_now_add=True)),
                ('responseAt', models.DateTimeField()),
                ('user_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_requested', to=settings.AUTH_USER_MODEL)),
                ('user_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_responded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
