# Generated by Django 5.1.5 on 2025-03-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moteurrecherche', '0003_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moteurrecherche.document'),
        ),
    ]
