# Generated by Django 5.1.5 on 2025-03-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moteurrecherche', '0004_permission_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='responseAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
