# Generated by Django 5.1.5 on 2025-03-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moteurrecherche', '0005_alter_permission_responseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
